---
# This default profile is used when running a single instance completely standalone:
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  config:
    activate:
      on-profile: default
---
spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: peer-1
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/,http://localhost:9003/eureka/

---
spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: peer-2
server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9003/eureka/

---
spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: peer-3
server:
  port: 9003
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
